# fly.toml app configuration file generated for financer-django on 2024-02-24T14:34:49-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'financer-django'
primary_region = 'eze'
console_command = '/code/manage.py shell'

#[deploy]
#release_command = "python manage.py migrate"

[env]
PORT = '8000'

[http_service]
internal_port = 8000
force_https = true
auto_stop_machines = true
auto_start_machines = true
min_machines_running = 0
processes = ['app']

[mounts]
source = "sqlite_db"
destination = "/mnt/sqlite_db"

[[vm]]
memory = '1gb'
cpu_kind = 'shared'
cpus = 1

[[statics]]
guest_path = '/code/static'
url_prefix = '/static/'
